import React from "react";
export const users = [
    {
        key: "1",
        purchase: "Released EP",
        story: "Story 1",
        task: "Task 5",
        cost:"40D",
      },
      {
        key: "2",
        purchase: "Rent",
        story: "n/a",
        task: "n/a",
        cost:"70D",
      },
      {
        key: "3",
        purchase: "Recording Equipment",
        story: "Story 3",
        task: "Task 1",
        cost:"10D",
      },
      {
        key: "4",
        purchase: "Advertisement",
        story: "Story 4",
        task: "Task 3 ",
        cost:"10D",
      },
      {
          key: "5",
          purchase: "Merchandise",
          story: "Story 5",
          task: "Task 2",
          cost: "20D",
        },
        {
          key: "6",
          purchase: "Studio Time",
          story: "Story 6",
          task: "Task 4",
          cost: "50D",
        },
        {
          key: "7",
          purchase: "Music Video",
          story: "Story 7",
          task: "Task 6",
          cost: "30D",
        },
        {
          key: "8",
          purchase: "Tour Expenses",
          story: "Story 8",
          task: "Task 7",
          cost: "100D",
        },
        {
          key: "11",
          purchase: "Graphic Design",
          story: "Story 20",
          task: "Task 1",
          cost: "5D",
        },
        {
          key: "12",
          purchase: "Photography",
          story: "Story 11",
          task: "Task 5",
          cost: "15D",
        },
        {
          key: "13",
          purchase: "Venue Booking",
          story: "Story 30",
          task: "Task 10",
          cost: "200D",
        },
        {
          key: "14",
          purchase: "Instrument Repairs",
          story: "Story 11",
          task: "Task 9",
          cost: "50D",
        },
        {
          key: "20",
          purchase: "Collaborations",
          story: "Story 19",
          task: "Task 8",
          cost: "90D",
        },
        {
          key: "21",
          purchase: "Music Lessons",
          story: "Story 20",
          task: "Task 9",
          cost: "80D",
        },
        {
          key: "22",
          purchase: "Networking Events",
          story: "Story 28",
          task: "Task 22",
          cost: "60D",
        },
        {
          key: "23",
          purchase: "Album Artwork",
          story: "Story 22",
          task: "Task 22",
          cost: "50D",
        },
        {
          key: "24",
          purchase: "Legal Fees",
          story: "Story 23",
          task: "Task 1",
          cost: "100D",
        },
        {
          key: "25",
          purchase: "Licensing",
          story: "Story 24",
          task: "Task 3",
          cost: "200D",
        },
        {
          key: "27",
          purchase: "Audience Surveys",
          story: "Story 25",
          task: "Task 2",
          cost: "5D",
        },
        {
          key: "29",
          purchase: "Demo Production",
          story: "Story 28",
          task: "Task 7",
          cost: "15D",
        },
        {
          key: "30",
          purchase: "Marketing Consultant",
          story: "Story 31",
          task: "Task 2",
          cost: "150D",
        },
];